package:
  format-version: "1.0.0"
  name: "csp_apps_pic32cxbz6_wbz6"
  type: "application"
  status: "beta"
  required: false
  version: "v3.0.0-E1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0-E1"
